### ISSUE TITLE
Problem with schema import

### ISSUE THREAD

**Issue by sbardascione** [arsarabi/jsonvectorizer#2]
Hi, i'm facing a problem when i try to execute your example file:

```
python example.py
Traceback (most recent call last):
  File "example.py", line 2, in <module>
    from jsonvectorizer import JsonVectorizer, vectorizers
  File "/home/company/vectorizer/jsonvectorizer/__init__.py", line 7, in <module>
    from .schema import Schema
ModuleNotFoundError: No module named 'jsonvectorizer.schema'

```

**Comment by arsarabi** [comment]
Sorry for the delayed response. In case this hasn't been resolved, it seems like Python is importing the local copy of the repository rather than the installed package. Make sure you have installed the package by running the setup script, and execute your code from outside the repository directory ("/home/company/vectorizer" in your case).
